### ISSUE TITLE
Herbert Ansible module

### ISSUE THREAD

**Issue by tazjin** [tazjin/herbert#10]
There should be an Ansible module for requesting and eventually deploying certificates from Herbert.

The module should be written in such a way that it doesn't halt the execution of other provisioning steps that don't depend on the Herbert certificate, for example by returning an object containing the state of the deployment that can be inspected by other steps.

I imagine this module to work something like this:

```
- name: Request certificate from Herbert
   herbert:
     name: logstash
     host: herbert.tazj.in
     subject: "{{ inventory_hostname }}"
     location: /etc/logstash.d/ 
```

This should create a private key using OpenSSL, create a CSR from the key and submit it to Herbert. These are stored in a temporary folder somewhere (where?) together with the ID received from Herbert.

On subsequent runs, the module will use the ID to check the state in Herbert. It will fetch the certificate once signed, or fail if the certificate request gets rejected.

The above example would create the certificate files as `/etc/logstash.d/logstash.crt` and `/etc/logstash.d/logstash.key`.
